### PR TITLE
pq.NullTime support

### PR DESCRIPTION
**Pull request by x88**

### CODE REVIEW

**Comment by biztos** [comment]
Please do merge this!  I was in the middle of writing more or less the same thing as your "null" when I discovered yours, so thank you very much for saving me the time!  However I will need NullTime so I guess I'll use x88's for now.

**Comment by bithavoc** [comment]
:+1:

**Comment by guregu** [comment]
Really sorry for leaving this un-looked-at. I wonder if this would be compatible with other types of SQL servers as well? I would prefer to keep this library compatible with all of them.

**Comment by bithavoc** [comment]
Well, I know gocql(Cassandra) and pq(postgresql) support time datatype

**Comment by andrewetter** [comment]
I used x88's fork, as well.  BTW - this PR will need the govet warning fix, as well. Reference: https://github.com/guregu/null/commit/41fe781af5dd0b14980914a13e7921643517d00f

**Comment by doxavore** [comment]
@guregu As far as I can tell, pq isn't doing anything special with regards to postgresql in its `pq.NullTime` type: https://github.com/lib/pq/blob/2997d165a566810a3b9e4d16e7cff1300f744c12/encode.go#L518

This seems to be the same exact method used throughout this project (and in database/sql), borderline generated code. Could we just recreate the type here and remove the runtime dependency on `pq` altogether?

(Sorry for the comment here and #7, I somehow missed this when commenting there....)

**Comment by guregu** [comment]
@doxavore Yes, I think that would be ideal. You're also right in that you could pretty much generate this whole project, might be worth looking into later.

**Comment by dustinsmith1024** [comment]
:+1:  I could use this too.

**Comment by guregu** [comment]
Added in #9.

**Pull request closed without merging**
