### PR TITLE
Code for .Float and .Int to handle numbers that come in as strings from json

### PR DESCRIPTION
**Pull request by chetan-prime**
Add ability like json.Number for .Float and .Int to handle numbers that come in as strings from the browser

### CODE REVIEW

**Comment by guregu** [comment]
Looks good to me, could you add some tests?

**Comment by chetan-prime** [comment]
Thanks , will add some code for testing json strings --> floats & ints

**Comment by chetan-prime** [comment]
The tests pass for me. I am not sure if I have covered all possibilities though

**Comment by guregu** [comment]
Thanks, I'll take a look soon

**Comment by chetan-prime** [comment]
Any issues with the code ? I have been using it for a few projects here and so far its been fine

**Comment by suntong** [comment]
Looks good and useful to me, too. 

Hope it'll get merged soon.

**Comment by guregu** [comment]
Sorry for the wait. I made added some tests and ran gofmt. I also added the equivalent changes to the zero package.

**Comment by suntong** [comment]
Wow, impressive, :+1:

**Comment by suntong** [comment]
Oh, forgot to say, 

maybe we should put `json` into github topics on the top of project page...

**Comment by chetan-prime** [comment]
Thanks, good to know that the functionality is now part of the master repo.
The wait was well worth it as I know its important not to make breaking changes for others using the same library

**Pull request merged**
